export type Language = 'en' | 'ar'

type Translation = {
  nav: { home: string; solutions: string; how: string; why: string; security: string; faq: string; cta: string }
  hero: { eyebrow: string; title: string; body: string; primary: string; secondary: string; trusted: string }
  stats: { volume: string; volumeLabel: string; businesses: string; businessesLabel: string; uptime: string; uptimeLabel: string }
  solutions: { eyebrow: string; title: string; body: string; items: { title: string; body: string }[] }
  how: { eyebrow: string; title: string; body: string; steps: { number: string; title: string; body: string }[] }
  why: { eyebrow: string; title: string; body: string; items: { title: string; body: string }[] }
  security: { eyebrow: string; title: string; body: string; items: string[] }
  dashboard: { label: string; balance: string; view: string; incoming: string; outgoing: string; volume: string; volumeValue: string; thisMonth: string; settled: string }
  cta: { title: string; body: string; primary: string; secondary: string }
  faq: { eyebrow: string; title: string; items: { question: string; answer: string }[] }
  footer: { body: string; solutions: string; company: string; resources: string; links: string[]; companyLinks: string[]; resourceLinks: string[]; copyright: string }
}

export const translations: Record<Language, Translation> = {
  en: {
    nav: { home: 'Home', solutions: 'Solutions', how: 'How it works', why: 'Why Pay Nest', security: 'Security', faq: 'FAQ', cta: 'Get started' },
    hero: { eyebrow: 'The infrastructure for what is next', title: 'Powering smarter digital payments', body: 'Simple, secure, and scalable payment solutions built for the digital economy.', primary: 'Get started', secondary: 'Explore solutions', trusted: 'Trusted by ambitious businesses across the region' },
    stats: { volume: '$2.4B+', volumeLabel: 'Payment volume processed', businesses: '18k+', businessesLabel: 'Businesses growing with us', uptime: '99.99%', uptimeLabel: 'Platform availability' },
    solutions: { eyebrow: 'One platform. Every possibility.', title: 'Payments that move at your pace', body: 'From your first transaction to your next million, Pay Nest gives your business the tools to move money with confidence.', items: [{ title: 'Online payments', body: 'Accept and manage digital payments through a simple, reliable payment infrastructure.' }, { title: 'Payment processing', body: 'Fast, secure transaction processing designed for the needs of modern businesses.' }, { title: 'Digital wallets', body: 'Modern wallet experiences that make every financial interaction more flexible.' }, { title: 'Business payments', body: 'Simplify your business payment operations with connected financial tools.' }, { title: 'Payment links', body: 'Create simple payment links and share them with customers without complex integrations.' }, { title: 'Digital finance', body: 'Flexible technology solutions that help businesses build their digital financial future.' }] },
    how: { eyebrow: 'Built to be easy', title: 'Payments, made effortless', body: 'A clear path from your first connection to lasting growth.', steps: [{ number: '01', title: 'Connect', body: 'Connect your business to the Pay Nest platform.' }, { number: '02', title: 'Start accepting', body: 'Start accepting digital payments through secure channels.' }, { number: '03', title: 'Grow further', body: 'Track transactions, simplify operations, and improve your customers’ payment experience.' }] },
    why: { eyebrow: 'Why Pay Nest', title: 'Designed for how money moves today', body: 'Everything you need to build better payment experiences, brought together in one thoughtful platform.', items: [{ title: 'Security first', body: 'Protect transactions and data with modern security practices.' }, { title: 'Fast & reliable', body: 'A seamless, dependable payment experience built for modern businesses.' }, { title: 'Easy integration', body: 'Technology designed to connect simply with your existing systems.' }, { title: 'Built to scale', body: 'Infrastructure ready to keep pace with your business.' }, { title: 'Real-time visibility', body: 'Get a clearer view of payment activity and transactions.' }, { title: 'Customer-centered', body: 'Create simple, smooth payment experiences for your customers.' }] },
    security: { eyebrow: 'A foundation you can trust', title: 'Security without the friction', body: 'Security is part of the Pay Nest experience. Our platform is shaped around modern security principles to help protect your transactions, data, and financial operations.', items: ['Secure transactions', 'Data protection', 'Fraud monitoring', 'Access control', 'Reliable infrastructure'] },
    dashboard: { label: 'Your business at a glance', balance: 'Available balance', view: 'View dashboard', incoming: 'Incoming', outgoing: 'Outgoing', volume: 'Payment volume', volumeValue: '$84,290', thisMonth: 'This month', settled: 'Settled' },
    cta: { title: 'Ready to simplify your digital payments?', body: 'Join the next generation of businesses building faster, easier, more connected payment experiences.', primary: 'Get started', secondary: 'Talk to us' },
    faq: { eyebrow: 'Questions, answered', title: 'Frequently asked questions', items: [{ question: 'What is Pay Nest?', answer: 'Pay Nest is a digital payments and fintech platform designed to simplify payment operations and create modern financial experiences.' }, { question: 'What solutions does Pay Nest offer?', answer: 'Pay Nest offers online payments, payment processing, digital wallets, payment links, and digital finance solutions for modern businesses.' }, { question: 'Who can use Pay Nest?', answer: 'Businesses and merchants of different sizes can use Pay Nest solutions according to their needs and requirements.' }, { question: 'Is Pay Nest secure?', answer: 'Pay Nest is designed with a focus on transaction security, data protection, and modern security practices.' }, { question: 'Can Pay Nest connect to existing systems?', answer: 'Yes. The platform is designed to integrate with your existing systems and services.' }, { question: 'How do I get started?', answer: 'Contact the Pay Nest team or select Get started to learn about the right next steps for your business.' }] },
    footer: { body: 'Modern digital payments and fintech solutions for a more connected world.', solutions: 'Solutions', company: 'Company', resources: 'Resources', links: ['Online payments', 'Payment processing', 'Digital wallets', 'Payment links', 'Business payments'], companyLinks: ['About us', 'Solutions', 'Security', 'Contact us', 'Careers'], resourceLinks: ['FAQ', 'Documentation', 'Support', 'Privacy policy', 'Terms & conditions'], copyright: '© 2026 Pay Nest. All rights reserved.' },
  },
  ar: {
    nav: { home: 'الرئيسية', solutions: 'الحلول', how: 'كيف نعمل', why: 'لماذا Pay Nest', security: 'الأمان', faq: 'الأسئلة الشائعة', cta: 'ابدأ الآن' },
    hero: { eyebrow: 'البنية التحتية لما هو قادم', title: 'نُمكّن مدفوعات رقمية أكثر ذكاءً', body: 'حلول دفع إلكتروني آمنة ومرنة وقابلة للتوسع، مصممة لتلبية احتياجات الاقتصاد الرقمي الحديث.', primary: 'ابدأ الآن', secondary: 'استكشف حلولنا', trusted: 'تحظى بثقة الشركات الطموحة في المنطقة' },
    stats: { volume: '2.4+ مليار دولار', volumeLabel: 'حجم المدفوعات المعالجة', businesses: '18 ألفًا+', businessesLabel: 'شركة تنمو معنا', uptime: '99.99%', uptimeLabel: 'توافر المنصة' },
    solutions: { eyebrow: 'منصة واحدة. إمكانات بلا حدود.', title: 'مدفوعات تتحرك بالسرعة التي تناسبك', body: 'من معاملتك الأولى إلى المليون التالية، نمنحك الأدوات لتحريك أموالك بثقة.', items: [{ title: 'المدفوعات الإلكترونية', body: 'استقبل وأدر المدفوعات الرقمية من خلال بنية دفع بسيطة وموثوقة.' }, { title: 'معالجة المدفوعات', body: 'معالجة سريعة وآمنة للمعاملات مصممة لتلبية احتياجات الأعمال الحديثة.' }, { title: 'المحافظ الرقمية', body: 'تجارب محافظ رقمية حديثة توفر طرقًا مرنة وسهلة لإجراء المعاملات المالية.' }, { title: 'مدفوعات الأعمال', body: 'بسّط عمليات الدفع الخاصة بأعمالك من خلال أدوات مالية رقمية متكاملة.' }, { title: 'روابط الدفع', body: 'أنشئ روابط دفع بسيطة وشاركها مع عملائك دون الحاجة إلى عمليات تكامل معقدة.' }, { title: 'الحلول المالية الرقمية', body: 'حلول تقنية مرنة تساعد الشركات على تطوير احتياجاتها المالية الرقمية.' }] },
    how: { eyebrow: 'مصممة لتكون سهلة', title: 'المدفوعات أصبحت أكثر سهولة', body: 'طريق واضح من اتصالك الأول إلى نمو أعمالك المستمر.', steps: [{ number: '01', title: 'اربط', body: 'اربط نشاطك التجاري بمنصة Pay Nest.' }, { number: '02', title: 'ابدأ استقبال المدفوعات', body: 'ابدأ في استقبال المدفوعات الرقمية من خلال قنوات دفع آمنة.' }, { number: '03', title: 'نمِّ أعمالك', body: 'تابع معاملاتك، وبسّط عمليات الدفع، وطوّر تجربة المدفوعات الرقمية الخاصة بك.' }] },
    why: { eyebrow: 'لماذا Pay Nest', title: 'مصمم للطريقة التي تتحرك بها الأموال اليوم', body: 'كل ما تحتاجه لبناء تجارب دفع أفضل، في منصة واحدة مدروسة.', items: [{ title: 'الأمان أولًا', body: 'حماية معاملاتك وبياناتك من خلال ممارسات أمنية حديثة.' }, { title: 'سرعة وموثوقية', body: 'تجربة دفع سلسة وموثوقة مصممة للأعمال الحديثة.' }, { title: 'سهولة التكامل', body: 'تقنيات مصممة لتسهيل الربط مع الأنظمة الحالية.' }, { title: 'قابلية التوسع', body: 'بنية تقنية قادرة على مواكبة نمو أعمالك.' }, { title: 'رؤية فورية', body: 'احصل على رؤية أوضح لنشاط المدفوعات والمعاملات.' }, { title: 'تجربة تركز على العميل', body: 'أنشئ تجارب دفع بسيطة وسلسة لعملائك.' }] },
    security: { eyebrow: 'أساس يمكنك الوثوق به', title: 'أمان يمكنك الوثوق به', body: 'الأمان جزء أساسي من تجربة Pay Nest. تم تصميم منصتنا وفق مبادئ أمنية حديثة للمساعدة في حماية المعاملات والبيانات والعمليات المالية.', items: ['معاملات آمنة', 'حماية البيانات', 'مراقبة الاحتيال', 'التحكم في الوصول', 'بنية تحتية موثوقة'] },
    dashboard: { label: 'نشاط أعمالك في لمحة', balance: 'الرصيد المتاح', view: 'عرض لوحة التحكم', incoming: 'الوارد', outgoing: 'الصادر', volume: 'حجم المدفوعات', volumeValue: '84,290 دولارًا', thisMonth: 'هذا الشهر', settled: 'تمت التسوية' },
    cta: { title: 'هل أنت مستعد لتبسيط مدفوعاتك الرقمية؟', body: 'انضم إلى الجيل الجديد من الشركات التي تعتمد على تجارب دفع أسرع وأسهل وأكثر ترابطًا.', primary: 'ابدأ الآن', secondary: 'تواصل معنا' },
    faq: { eyebrow: 'إجابات عن أسئلتك', title: 'الأسئلة الشائعة', items: [{ question: 'ما هي Pay Nest؟', answer: 'Pay Nest هي منصة متخصصة في حلول الدفع الإلكتروني والتكنولوجيا المالية الرقمية، وتهدف إلى تبسيط عمليات الدفع وتوفير تجارب مالية رقمية حديثة.' }, { question: 'ما الحلول التي تقدمها Pay Nest؟', answer: 'توفر Pay Nest مجموعة من حلول الدفع الإلكتروني والخدمات المالية الرقمية المصممة لتلبية احتياجات الشركات والأعمال الحديثة.' }, { question: 'من يمكنه استخدام Pay Nest؟', answer: 'يمكن للشركات والأنشطة التجارية المختلفة الاستفادة من حلول Pay Nest وفقًا لاحتياجاتها ومتطلباتها.' }, { question: 'هل Pay Nest آمنة؟', answer: 'تم تصميم Pay Nest مع التركيز على أمان المعاملات وحماية البيانات واستخدام ممارسات أمنية حديثة.' }, { question: 'هل يمكن ربط Pay Nest بالأنظمة الحالية؟', answer: 'نعم، صُممت المنصة بحيث تكون قابلة للتكامل مع الأنظمة والخدمات الحالية.' }, { question: 'كيف يمكنني البدء؟', answer: 'يمكنك التواصل مع فريق Pay Nest أو الضغط على ابدأ الآن لمعرفة الخطوات المناسبة لنشاطك.' }] },
    footer: { body: 'حلول حديثة للدفع الإلكتروني والتكنولوجيا المالية الرقمية لعالم أكثر اتصالًا.', solutions: 'الحلول', company: 'الشركة', resources: 'الموارد', links: ['المدفوعات الإلكترونية', 'معالجة المدفوعات', 'المحافظ الرقمية', 'روابط الدفع', 'مدفوعات الأعمال'], companyLinks: ['من نحن', 'الحلول', 'الأمان', 'تواصل معنا', 'الوظائف'], resourceLinks: ['الأسئلة الشائعة', 'التوثيق', 'الدعم', 'سياسة الخصوصية', 'الشروط والأحكام'], copyright: '© 2026 Pay Nest. جميع الحقوق محفوظة.' },
  },
}
